**TensorFlow Basics**

In [43]:
import tensorflow as tf
import numpy as np 

In [44]:
# Make Sure you are using 2.3.0 for exact syntex matching!
print(tf.__version__)

2.8.0


**HelloWorld**

In [45]:
hello = tf.constant('Hello')

In [46]:
type(hello)

tensorflow.python.framework.ops.EagerTensor

In [47]:
world = tf.constant('World')

In [48]:
result = hello + world

In [49]:
result

<tf.Tensor: shape=(), dtype=string, numpy=b'HelloWorld'>

In [50]:
type(result)

tensorflow.python.framework.ops.EagerTensor

In [59]:

with tf.compat.v1.Session() as sess:
    result = tf.constant('hello world')
    print(sess.run(result))    

b'hello world'


**Computations**

In [61]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [62]:
type(tensor_1)

tensorflow.python.framework.ops.EagerTensor

In [63]:
tensor_1 + tensor_2

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [64]:
sess

In [65]:
sess.close()

**Matrix Multiplication**

In [66]:
a = tf.constant([[1,2],
                [3,4]])

In [67]:
a.get_shape()

TensorShape([2, 2])

In [68]:
b = tf.constant([[10],[100]])

In [69]:
b.get_shape()

TensorShape([2, 1])

In [70]:
result = tf.matmul(a,b)

In [74]:
tf.print(result)

[[210]
 [430]]
